aws_region = "us-east-2"
cust_name  = "ahead"
app  = "celfie"
environment="acceptance"
state_bucket         = "ahead-terraform-state"
state_key            = "terraform.tfstate"
state_dynamodb_table = "ahead-terraform-locks"
