name: Terraform CI/CD
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "acceptance"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::646738440247:role/github-terraform-role
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init -backend-config=backend-${{ github.event.inputs.environment }}.hcl
      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars" -out=tfplan
      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  terraform-apply:
    name: Terraform Apply (Manual Approval)
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: apply
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::646738440247:role/github-terraform-role
          aws-region: us-east-1
      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
            name: tfplan
            path: .  
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan