name: Terraform CI/CD
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "acceptance"
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Set environment-specific branch
        id: set_branch
        run: |
          case "${{ github.event.inputs.environment }}" in
            acceptance)
              echo "branch=ENV-Acceptance" >> $GITHUB_OUTPUT
              echo "AWS_ACCOUNT=${{ vars.ACCEPTANCE_ACCOUNT }}" >> $GITHUB_ENV
              ;;
            production)
              echo "branch=ENV-Prod" >> $GITHUB_OUTPUT
              echo "AWS_ACCOUNT=${{ vars.PROD_ACCOUNT }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment" && exit 1
              ;;
          esac
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set_branch.outputs.branch }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-terraform-role
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init -backend-config=backend-${{ github.event.inputs.environment }}.hcl
      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars" -out=tfplan
      - name: List files in workspace
        run: ls -ltra
      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan  

  terraform-apply:
    name: Terraform Apply (Manual Approval)
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: ${{github.event.inputs.environment}}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set environment-specific branch
        id: set_branch
        run: |
          case "${{ github.event.inputs.environment }}" in
            acceptance)
              echo "branch=ENV-Acceptance" >> $GITHUB_OUTPUT
              echo "AWS_ACCOUNT=${{ vars.ACCEPTANCE_ACCOUNT }}" >> $GITHUB_ENV
              ;;
            production)
              echo "branch=ENV-Prod" >> $GITHUB_OUTPUT
              echo "AWS_ACCOUNT=${{ vars.PROD_ACCOUNT }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment" && exit 1
              ;;
          esac
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set_branch.outputs.branch }}
      - name: Show current Git branch
        run: |
          echo "Branch from Git:"
          git branch
          echo "Full GitHub ref:"
          echo "${GITHUB_REF}"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-terraform-role
          aws-region: us-east-1
      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
            name: tfplan
            path: .
      - name: Terraform Init
        run: terraform init -backend-config=backend-${{ github.event.inputs.environment }}.hcl      
      - name: Terraform Apply
        run: terraform apply -var-file="${{ github.event.inputs.environment }}.tfvars" -auto-approve tfplan